<theme extends="webstandard" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="platform:/plugin/com.ibm.designer.domino.stylekits/schema/stylekit.xsd" >
	
	<!-- overrides for resource aggregation -->
	<resource rendered="#{javascript:context.getProperty('xsp.resources.aggregate').equals('true')}">
		<content-type>text/css</content-type>
		<href>aggregate.css</href>
	</resource>
	
</theme>
